version: "3"
services:
  imperiumcms:
    build: .
    ports:
      - "8080:8080"
    links:
      - "imperiumdb:db"
    volumes:
      - .:/app
    env_file:
      - .env
  imperiumdb:
    container_name: imperiumdb
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always